@echo off
cd web
echo Eliminazione node_modules...
if exist node_modules rmdir /s /q node_modules
echo Eliminazione package-lock.json...
if exist package-lock.json del package-lock.json
echo Installazione dipendenze...
npm install
echo Avvio server di sviluppo...
npm run dev
